adds Definition of Done
project-leek/project-leek pull request #151
Opened 2020-12-14 13:57 UTC by JanEberlein

2020-12-14 20:00 UTC, tcoro requested changes

2020-12-14 20:00 UTC, tcoro commented on docs/Definition-of-Done.md
> + - the changes have been reviewed and approved by two reviewers
maybe this is better?
```suggestion
 - the changes have been reviewed and approved by atleast two reviewers
```

2020-12-14 20:00 UTC, tcoro commented on docs/Definition-of-Done.md
> +- the changes are pushed to its branch (created when assigning yourself)
```suggestion
- the changes are pushed to its branch (automated on first issue assignment)
```

2020-12-14 20:00 UTC, tcoro commented on docs/Definition-of-Done.md
> +Only then can the issue be closed (can be done via PR).
```suggestion
The issue can be closed with a PR after completing all steps above.
```

2020-12-14 20:00 UTC, tcoro commented on docs/Definition-of-Done.md
> +A milestone was finished successfully when:
you are using past tense here, and then present in the points afterwards

```suggestion
A milestone is finished successfully when:
```

2020-12-14 20:43 UTC, JanEberlein commented on docs/Definition-of-Done.md
> + - the changes have been reviewed and approved by two reviewers
yes 😄

2020-12-14 20:54 UTC, tcoro approved these changes

2020-12-15 11:13 UTC, anbraten requested changes

2020-12-15 11:13 UTC, anbraten commented on docs/Definition-of-Done.md
> +A milestone is finished successfully when:
```suggestion
If following points apply, a milestone can be treated as done:
```

2020-12-21 12:25 UTC, JanEberlein commented on docs/Definition-of-Done.md
> +- the changes are pushed to its branch (automated on first issue assignment)
```suggestion
- the changes are pushed to its branch (automated on first issue assignment)
- the changes are documented sufficiently
```

2020-12-22 10:10 UTC, anbraten approved these changes

2020-12-22 10:10 UTC, merged