- adds tag detail view and corresponding route
project-leek/project-leek pull request #224
Opened 2021-01-04 13:45 UTC by JanEberlein

2021-01-05 21:14 UTC, julianhahn requested changes

2021-01-05 21:14 UTC, julianhahn commented on packages/app/src/views/TagDetails.vue
> +import { defineComponent, ref } from 'vue';
`
```suggestion
import { defineComponent } from 'vue';
```

unused ref

2021-01-05 21:14 UTC, julianhahn commented on packages/app/src/router/index.ts
> +    path: '/tag-details/:id',
```suggestion
    path: '/tag/:id',
```

I would remove hypfen from the uri.

2021-01-05 21:17 UTC, julianhahn commented on packages/app/src/views/TagDetails.vue
> +import { defineComponent, ref } from 'vue';
Sorry, didn't see this was on draft

2021-01-18 15:24 UTC, JanEberlein commented on packages/app/src/router/index.ts
> +    path: '/tag-details/:id',
good idea

2021-01-27 12:49 UTC, tcoro requested changes
good work, just minor UI changes:

![image](https://user-images.githubusercontent.com/9517685/105993204-5f9e9c80-60a6-11eb-8804-7558d9c264dc.png)

why is there white whitespace left and right?
and could you hide the scrollbar?
edit: also the footer and header have different heights compared to other views

2021-01-27 16:28 UTC, JanEberlein commented
> good work, just minor UI changes:
> 
> why is there white whitespace left and right?
> and could you hide the scrollbar?
> edit: also the footer and header have different heights compared to other views
> edit2: I would put the change image button next to the image, not below it, better us of the whitespace. Or make the image the whole width

working on it

2021-01-27 19:38 UTC, JanEberlein commented
> > good work, just minor UI changes:
> > why is there white whitespace left and right?
> > and could you hide the scrollbar?
> > edit: also the footer and header have different heights compared to other views
> > edit2: I would put the change image button next to the image, not below it, better us of the whitespace. Or make the image the whole width
> 
> working on it

done (except for uniform header and footer sizes, I opened issue #325 for that)

2021-01-27 20:12 UTC, julianhahn approved these changes
looks good, now with working checks for empty fields

2021-01-27 20:35 UTC, tcoro approved these changes
looks good

2021-01-27 20:37 UTC, merged