Update and prepare report work
project-leek/project-leek pull request #245
Opened 2021-01-11 10:07 UTC by tcoro

updated sections so that in master are all draft sections visible
added more sections from GPM

2021-01-11 17:24 UTC, schnickalodeon approved these changes

2021-01-13 10:23 UTC, JanEberlein requested changes

2021-01-13 10:23 UTC, JanEberlein commented on docs/report/report.tex
> +\colorbox{red}{ticket pool in github, alles zentral, 3x daily standup, gemeinsamer google calendar, interne team evaluation und feedback}
```suggestion
\colorbox{red}{ticket pool in github, gemeinsame Absprache (im team und mit Kunden) was in den aktuellen Milestone kommen soll, alles zentral, 3x daily standup, gemeinsamer google calendar, gemeinsamer Discord Server (für spontaneres und informelleres gemeinsames Arbeiten), interne team evaluation und regelmäßiges feedback}
```

2021-01-13 10:23 UTC, JanEberlein commented on docs/report/report.tex
> +\colorbox{red}{Tests halt, bau mal alles zusammen undso. Wurde am Ende aber auch mehr Hand in Hand mit der vorherigen gemacht}
```suggestion
\subsubsection{Realisierungsphase}
\colorbox{red}{Iteratives Arbeiten in Meilensteinen/Sprint mit Länge ca. 2 Wochen. Coden etc. Jedes Arbeitspaket wird einzeln getestet und von mindestens zwei anderen Personen reviewt (Technische Funktionalität wird automatisch getestet)}
```
Ich stimme zu, dass das Testen und Coden Hand in Hand ging und würde dementsprechend auch die Berichtsabschnitte zusammenlegen. Ich würde auch sagen, dass wir rausstellen dass wir im Hauptteil iterativ arbeiten (Sprints)

2021-01-13 10:23 UTC, JanEberlein commented on docs/report/report.tex
> +\subsubsection{Vermarktungsphase}
Ich finde den Begriff "Vermarktung" irgendwie fehl am Platz, wir wollen ja nix verkaufen (nur so ein Gefühl), aber ich hab momentan leider auch keine bessere Idee 😅 Ich hatte über 'Finalisierungsphase' nachgedacht, aber das passt auch nicht wirklich

2021-01-13 16:11 UTC, JanEberlein approved these changes

2021-01-13 16:26 UTC, merged