292 create a new state which visualise that a tag is selected
project-leek/project-leek pull request #295
Opened 2021-01-20 20:39 UTC by julianhahn

Todo:

- [ ] unselect if another group is choosen

- [ ] bug on delete

2021-01-22 15:25 UTC, anbraten requested changes
Nice work. If you already planned to refactor stuff I just commented, please ignore them

2021-01-22 15:25 UTC, anbraten commented on packages/app/src/components/uiBlocks/GroupDropDownItem.vue
> +    watch(isOpen, (newVal) => {
I would change this, so that you emit some `isOpen` event to the parent which then can set the `selectedTag` to `null`.

2021-01-22 15:25 UTC, anbraten commented on packages/app/src/views/Home.vue
> +      buttonTransitionActive.value = true;
Could you put that into the template as you did it with `@leave` for `infoTransitionActive`.

2021-01-25 15:11 UTC, anbraten approved these changes
lgtm 👍🏾 
thanks for your changes

2021-01-25 15:23 UTC, tcoro approved these changes
🏑 🍙 🥅

2021-01-25 15:24 UTC, merged