Fix report latex build
project-leek/project-leek pull request #307
Opened 2021-01-25 15:12 UTC by tcoro

2021-01-25 15:34 UTC, JanEberlein requested changes

2021-01-25 15:34 UTC, JanEberlein commented on docs/report/report.tex
> +Deezer lässt sich vergleichbar zu Spotify über eine API steuern.\footnote{http://developers.deezer.com/login?redi{TODO:}ect=/api}
```suggestion
Deezer lässt sich vergleichbar zu Spotify über eine API steuern.\footnote{http://developers.deezer.com/login?redirect=/api}
```
find and replace error 😆

2021-01-25 15:37 UTC, tcoro commented on docs/report/report.tex
> +Deezer lässt sich vergleichbar zu Spotify über eine API steuern.\footnote{http://developers.deezer.com/login?redi{TODO:}ect=/api}
woops

2021-01-26 14:42 UTC, anbraten approved these changes

2021-01-26 17:27 UTC, JanEberlein approved these changes

2021-01-26 17:29 UTC, merged