166 implement UI for searching tags
project-leek/project-leek pull request #311
Opened 2021-01-26 09:47 UTC by tcoro

Implement the search bar according to the [figma](https://www.figma.com/file/RevVhXP9iyGxmch31H0Tce/Project-Leek?node-id=115%3A341) mockup:

- [ ] create search bar
- [ ] implement into tag overview
- [ ] implement functionality of filtering

2021-01-26 19:18 UTC, schnickalodeon commented on packages/app/src/components/add-tag/AddTagStepTrack.vue
> +      tagCopy.trackArtists = track.artists.join(', ');
Later we can (should change this)
In the PR #224 Implement UI for editing a tag I added a service to get the 

- title
- Artists

by the spotify uri

2021-01-26 19:23 UTC, schnickalodeon commented on packages/app/src/components/uiBlocks/TagSearchResult.vue
> +    const searchResult = ref<NFCTag[]>([]);
Later we can (should change this)
In the PR #224 Implement UI for editing a tag I added a service to get the 

Then:

 const selectedTrack = ref<SpotifyTrack>();

2021-01-26 19:27 UTC, schnickalodeon commented on packages/commons/src/nfc-tag.class.ts
> +
Later remove this

2021-01-26 19:28 UTC, schnickalodeon approved these changes

2021-01-26 19:47 UTC, julianhahn requested changes
something is wrong with the overflow on the right side. Please fix this

![image](https://user-images.githubusercontent.com/40185075/105896829-a1cccd00-6017-11eb-9bb0-9fe7619d6812.png)

2021-01-26 21:28 UTC, tcoro commented
> something is wrong with the overflow on the right side. Please fix this
> 
> ![image](https://user-images.githubusercontent.com/40185075/105896829-a1cccd00-6017-11eb-9bb0-9fe7619d6812.png)

I tried to replicate your problem and did not find the problem?
And just with looking at the code I couldnt find the possible line which produces this problem 
![image](https://user-images.githubusercontent.com/9517685/105907676-89fc4580-6025-11eb-8019-abfacf20cfe3.png)

2021-01-27 08:28 UTC, tcoro commented
@julianhahn it now looks like this:
![image](https://user-images.githubusercontent.com/9517685/105964050-fefd6880-6081-11eb-8da7-4ed28ca5dd9a.png)

2021-01-27 10:30 UTC, julianhahn approved these changes

2021-01-27 10:33 UTC, merged