- modified readme
project-leek/project-leek pull request #33
Opened 2020-11-09 14:01 UTC by JanEberlein

closes Add 'How to contribute' section to readme #32

2020-11-09 14:28 UTC, anbraten requested changes

2020-11-09 14:28 UTC, anbraten commented on README.md
> +
```suggestion
## How to contribute 

### For externals

TBD 🤔 

### For official team members

Always check for open [code-reviews](https://github.com/project-leek/project-leek/pulls?q=is%3Aopen+is%3Apr+type%3Apr+review%3Arequired) and do them if available before you start with a new issue.

#### How to start with a new issue

1. choose an open issues from the [project boards Todo column](https://github.com/project-leek/project-leek/projects/1)
1. 👉🏾 assign the issue to yourself 
1. create a local branch with name: issue-number (without hash) + "-" + issue-title (e.g. 8-setup-mono-repo)
1. 👨🏾 👩🏾 ✍🏾 💻 
1. ⬆️ commit + push 
1. in [pull-requests](https://github.com/project-leek/project-leek/pulls): create pull-request for current changes (from your branch to master) (there should be a button)
1. 🕙 wait for at least 2 other contributors to review your code and for the automated pipeline to finish
1. 🥗 merge your pull-request
1. 😃 be happy to be a part of this project
```

2020-11-09 14:42 UTC, anbraten approved these changes

2020-11-09 14:50 UTC, anbraten requested changes
sorry think it would be nice to add this change as well 😂

2020-11-09 14:50 UTC, anbraten commented on README.md
> +1. in [pull-requests](https://github.com/project-leek/project-leek/pulls): create pull-request for current changes (from your branch to master) (there should be a button)
```suggestion
1. create a new pull-request
  1. go to [pull-requests](https://github.com/project-leek/project-leek/pulls)
  1. there should be a button to create a pull-request for your changes (from your branch to master)
  1. add a description to you pull-request starting with `closes #<number-of-your-issue>` exp: `closes #1234`  
```

2020-11-11 14:51 UTC, schnickalodeon requested changes
A few request changes...

2020-11-11 14:51 UTC, schnickalodeon commented on README.md
> +1. create a local branch with name: issue-number (without hash) + "-" + issue-title (e.g. 8-setup-mono-repo)
That's not needed anymore
```suggestion
1. At the moment you assign the issue, a local branch with an auto-generated title will be created for you.
```

2020-11-11 14:51 UTC, schnickalodeon commented on README.md
> +1. 👨🏾 👩🏾 ✍🏾 💻
Thats not clear enough.
```suggestion
1. 👨🏾 👩🏾 ✍🏾 💻 ☕  (start coding)
```

2020-11-11 14:56 UTC, schnickalodeon approved these changes
That's ok

2020-11-11 14:59 UTC, anbraten approved these changes

2020-11-11 14:59 UTC, merged