381 edit tag change image when song is changed
project-leek/project-leek pull request #387
Opened 2021-02-05 16:32 UTC by schnickalodeon

closes #381 

Change the image if track is changed **and** the selected image isn't an external one

2021-02-05 16:59 UTC, tcoro approved these changes
n 🍨 🧊 🍦

2021-02-05 17:44 UTC, anbraten requested changes
Nice change.
One bug I noticed. If you select a tag at the home screen and choose edit your are getting redirect to the track selection instead of the tag-details page.

And one question: If I selected a special custom image I really like and now switch the track I would loose my image as well?

2021-02-06 11:09 UTC, schnickalodeon commented on packages/app/src/main.ts
>  import '@fontsource/baloo-2/700.css'; // TODO disable font to get rid of an error
Thanks therefore. Strangely enough, I've encoutered that bug as well and changed that. But that wasn't merged ^^

And No, the image will only be replaced if the former image was an Spotify-Image (cp. Description ;)

2021-02-06 11:57 UTC, anbraten requested changes
🤔  this change doesn't work for me.

2021-02-06 12:40 UTC, schnickalodeon commented
> 🤔 this change doesn't work for me.

Yes I see. I found the issue

2021-02-07 16:43 UTC, JanEberlein approved these changes
Looks good 👍

2021-02-07 19:42 UTC, anbraten approved these changes

2021-02-07 19:44 UTC, merged