Adds No nfc-tags text in home
project-leek/project-leek pull request #401
Opened 2021-02-07 18:51 UTC by schnickalodeon

closes #397

2021-02-07 19:15 UTC, anbraten requested changes

2021-02-07 19:15 UTC, anbraten commented on packages/app/src/views/Home.vue
> +          </p>
```suggestion
          <p>Huch, da sind ja keine NFC Tags!</p>
          <p>Füge fix einen hinzu!</p>
```

2021-02-07 19:15 UTC, anbraten commented on packages/app/src/views/Home.vue
> +        <span></span>
```suggestion
```

2021-02-07 19:15 UTC, anbraten commented on packages/app/src/views/Home.vue
> +        <span class="text-white font-heading text-2xl">
```suggestion
        <div class="text-white font-heading text-2xl">
```

2021-02-07 19:15 UTC, anbraten commented on packages/app/src/views/Home.vue
> +        </span>
```suggestion
        </div>
```

2021-02-08 10:29 UTC, tcoro requested changes
I agree with @anbraten

2021-02-08 11:37 UTC, tcoro approved these changes
good

2021-02-08 13:29 UTC, anbraten approved these changes

2021-02-08 13:29 UTC, merged