Report: Einleitung
project-leek/project-leek pull request #411
Opened 2021-02-08 21:31 UTC by JanEberlein

ich bin persönlich nicht der Meinung, dass wir in der Einleitung den Aufbau des Berichts erläutern sollten. Das passiert schon durch die allgemeine Struktur und das Inhaltsverzeichnis. 
Die Einleitung ist momentan mehr ne kurze Hinleitung zu dem gesamten Konzept "PROI". Ist auch nicht all zu lang.

2021-02-09 12:02 UTC, schnickalodeon commented on docs/report/report.tex
> +Ein zentraler Teil des Studiengangs "Informationstechnologien" ist es, Softwareentwicklung in Teams und Kommunikation mit Kund:innen zu erlernen. \cite{Qualifikationsziele_Informationstechnologien}
```suggestion
Ein zentraler Teil des Studiengangs \glqq Informationstechnologien\grqq{} ist es, Softwareentwicklung in Teams und Kommunikation mit Kund:innen zu erlernen. \cite{Qualifikationsziele_Informationstechnologien}
```

2021-02-09 12:02 UTC, schnickalodeon commented on docs/report/report.tex
> +Dies passiert vor allem im Modul "Projekt Informatik (PROI)".
```suggestion
Dies passiert vor allem im Modul \glqq Projekt Informatik (PROI)\grqq{}.
```

2021-02-09 12:04 UTC, schnickalodeon requested changes
Gefällt mir gut. 

Nur bitte die Änderung mit den Anführungszeichen durchführen :)

2021-02-09 17:58 UTC, tcoro approved these changes
nices intro

2021-02-10 19:08 UTC, schnickalodeon commented on docs/report/literature.bib
> +@online{Qualifikationsziele_Informationstechnologien,
```suggestion
@online{Qualifikationsziele_Informationstechnologie,
```

2021-02-10 19:09 UTC, schnickalodeon requested changes
Nur noch ein kleiner Buchstabe :D

2021-02-10 19:10 UTC, schnickalodeon approved these changes
Perfekt :)

2021-02-10 19:11 UTC, merged