422 durchfuehrung technologien
project-leek/project-leek pull request #427
Opened 2021-02-11 10:49 UTC by schnickalodeon

Entstand aus #374 (war zu groß)

closes #422

2021-02-11 17:50 UTC, JanEberlein requested changes
größtenteils Kleinkram, sonst ist alles gut

2021-02-11 17:50 UTC, JanEberlein commented on docs/report/report.tex
> +\cite{Tailwind_Vorteile}
```suggestion
Zur Vereinfachung der Gestaltung der Verwaltungsoberfläche einigte sich das Team auf die Nutzung des Utility-First-Frameworks \textit{TailwindCSS}\footnote{url{https://tailwindcss.com}}.
Dieses bietet im Vergleich zu anderen CSS-Frameworks wie \textit{Bootstrap} mehr Flexibilität, weil statt vorgefertigten Komponenten vielseitig verwendbare Utility-Klassen zur Verfügung gestellt werden, über die das Design definiert werden kann.
So kann das Aussehen von Elementen innerhalb des HTML-Codes festgelegt werden. Damit steigt die Übersichtlichkeit des Frontend-Codes, da keine separaten CSS-Dateien und -Klassen angelegt werden müssen.
\cite{Tailwind_Vorteile}
```

2021-02-11 17:50 UTC, JanEberlein commented on docs/report/report.tex
> +\colorbox{red}{Da nochmal rübergucken}
```suggestion
Um den Nutzer:innen die Installation der Box möglichst einfach zu machen, wird auf die freie Containervirtualisierungssoftware \textit{Docker}\footnote{https://www.docker.com/} gesetzt.
Ohne diese Möglichkeit wäre die Installation der 3 Microservices (Backend, Reverse-Proxy und NFC-Reader) sehr aufwändig.
Der Vorteil von Docker besteht darin, dass das Team lediglich ein sogenanntes \textit{docker-compose} file benötigt, in dem die Konfiguration der Docker-Container beschrieben ist.
Es enthält das jeweilige Image, auf dem der Container aufbaut (z. B. ngroc - für den Reverse-Proxy). Dieses Image enthält schon alle notwendigen Abhängigkeiten und Programme, sodass die Benutzer:innen diese nicht
selbst installieren müssen. Neben dem Image sind noch Informationen über die weitergeleiteten Ports (zur Kommunikation zwischen den einzelnen Containern und nach \colorbox{red}{draußen}) und die verwendeten
Laufwerke. Neben der einfachen Auslieferung bietet Docker außerdem den Vorteil, dass Fehler, die bei einem Entwickler auftreten bei anderen reproduzierbar sind, da die Software nicht auf unterschiedlichen
Systemen, sondern immer auf dem gleichen System läuft (dem/der Container)
\colorbox{red}{Da nochmal rübergucken}
```
Inhaltlich kann ich leider auch nicht mehr beitragen 😅

2021-02-12 10:33 UTC, schnickalodeon commented on docs/report/report.tex
> +clientseitigen JavaScript-Webframeworks \textit{Vue.js}\footnote{\raggedright\url{https://vuejs.org/}}
also theoretisch müsste es eher heißen: "[...]die zum Verwalten der NFC-Tags und Steuern der Ausgabegeräte genutzt **wird** [...]" (Sie wird es ja auch in Zukunft noch

2021-02-13 14:05 UTC, JanEberlein requested changes

2021-02-13 14:05 UTC, JanEberlein commented on docs/report/report.tex
> +Dies ist notwendig, da moderne Browser eine verschlüsselte Verbindung (mit SSL-Zertifikat) zu allen Komponenten auf der Website verlangen, sobald die Website selbst per SSL geladen wird.
```suggestion
Dies ist notwendig, da moderne Browser eine verschlüsselte Verbindung (mit SSL-Zertifikat) zu allen Komponenten auf der Website verlangen, sobald die Website selbst per SSL geladen wird.
Eine solche Verbindung konnte nicht mit der \textit{leek-box} hergestellt werden, da \colorbox{red}{warum nicht}
```
Ich hab das nicht mehr im Kopf, deswegen die colorbox 😅

2021-02-13 14:05 UTC, JanEberlein commented on docs/report/report.tex
> +Es enthält einen Verweis auf die jeweiligen Images, auf denen die Container aufbauen (z. B. leek-backend). Diese Images enthalten bereits alle notwendigen Abhängigkeiten und Programme,
```suggestion
Es enthält einen Verweis auf die jeweiligen System-Images, auf denen die Container aufbauen (z. B. leek-backend). Diese Images enthalten bereits alle notwendigen Abhängigkeiten und Programme,
```

2021-02-13 19:54 UTC, schnickalodeon commented on docs/report/report.tex
> +Neben der Programmiersprache Typescript setzte das Team verschiedene Frameworks ein, um bei der Entwicklung auf bereits existierenden Lösungenmit weniger Aufwand zu entwickeln.
Ich bin echt zu blöd ^^

2021-02-13 19:59 UTC, schnickalodeon commented on docs/report/report.tex
> +Das Framework \textit{FeathersJS}\footnote{\raggedright\url{https://feathersjs.com/}} ermöglicht komfortable CRUD-Zugriffe\footnote{CRUD = \textbf{C}reate-\textbf{R}ead-\textbf{U}pdate-\textbf{D}elet
Guter Ansatz: ich werde es ändern zu:

Bei der Erstellung des Backends entschied sich das Team zusätzlich das Framework FeathersJS einzusetzten.
Sonst klingt es so, als wäre bestehe das Backend NUR aus Feathers 😄

2021-02-13 20:00 UTC, schnickalodeon commented on docs/report/report.tex
> +  \protect\cite{}
Nö, ich bin nur ein Otto und habe vergessen die Quelle anzugeben ^^

2021-02-14 12:26 UTC, schnickalodeon commented on docs/report/report.tex
> +  \protect\cite{}
Wird geändert ^^

2021-02-14 12:28 UTC, schnickalodeon commented on docs/report/report.tex
> +Eine weiteres Feature, welches vom Projektteam genutzt wurde ist die integrierte OAuth-Provider-Abstraktionen, die ein einfaches Authentifizieren mit Diensten wie in unserem Fall \textit{Spotify} erm
Soll ich jetzt genau schreiben, wie OAuth funktioniert?
Ich glaube das führt etwas zu weit.

2021-02-14 12:32 UTC, schnickalodeon commented on docs/report/report.tex
> +Dies ist notwendig, da moderne Browser eine verschlüsselte Verbindung (mit SSL-Zertifikat) zu allen Komponenten auf der Website verlangen, sobald die Website selbst per SSL geladen wird.
Jo, ergänze ich

2021-02-14 12:33 UTC, schnickalodeon commented on docs/report/report.tex
> +Es enthält einen Verweis auf die jeweiligen Images, auf denen die Container aufbauen (z. B. leek-backend). Diese Images enthalten bereits alle notwendigen Abhängigkeiten und Programme,
Was meinst du mit System Image?

2021-02-14 15:17 UTC, JanEberlein commented on docs/report/report.tex
> +Es enthält einen Verweis auf die jeweiligen Images, auf denen die Container aufbauen (z. B. leek-backend). Diese Images enthalten bereits alle notwendigen Abhängigkeiten und Programme,
eigentlich nur das selbe wie du, nur expliziter. Container-Image wäre klarer gewesen.

2021-02-14 15:18 UTC, JanEberlein commented on docs/report/report.tex
> +Eine weiteres Feature, welches vom Projektteam genutzt wurde ist die integrierte OAuth-Provider-Abstraktionen, die ein einfaches Authentifizieren mit Diensten wie in unserem Fall \textit{Spotify} erm
Ne OAuth wäre zu viel. Aber erläutern warum das gut für unser Projekt ist, sollten wir schon

2021-02-14 15:26 UTC, schnickalodeon commented on docs/report/report.tex
> +Es enthält einen Verweis auf die jeweiligen Images, auf denen die Container aufbauen (z. B. leek-backend). Diese Images enthalten bereits alle notwendigen Abhängigkeiten und Programme,
Jo :)

2021-02-14 15:35 UTC, JanEberlein approved these changes
Nice Work 😄

2021-02-14 19:13 UTC, tcoro approved these changes

2021-02-14 19:17 UTC, tcoro commented
@schnickalodeon , magst du mal die conflicts anschauen?
Ist ja nichts großes, aber bevor ich was falsches lösche

2021-02-15 08:12 UTC, merged