Anmerkungen zum Bericht
project-leek/project-leek pull request #458
Opened 2021-02-16 19:41 UTC by JanEberlein

ich hab mal alles* mehr oder minder grob durchgelesen und ein paar inhaltliche Anmerkungen hinterlassen.
*: Ich hab die teile Projektmanagement und testing nicht gelesen (hab ich selber verbockt, das geht mir dann irgendwie zu sehr gegen den Strich)

2021-02-17 10:01 UTC, schnickalodeon commented
Ich übernehme Projektmanagement und Testing

2021-02-17 12:11 UTC, tcoro approved these changes

2021-02-21 14:48 UTC, tcoro requested changes
orange als colorbox geht nicht

2021-02-21 14:48 UTC, tcoro commented on docs/report/report.tex
> +\colorbox{orange}{Ja und? warum ist das relevant? was bedeutet das für unser Projekt}
```suggestion
\colorbox{red}{Ja und? warum ist das relevant? was bedeutet das für unser Projekt}
```

2021-02-21 14:48 UTC, tcoro commented on docs/report/report.tex
> +\colorbox{orange}{Abschnitt: allgemeiner formulieren. Am Anfang wurde abgesprochen, dass es auch andere Services geben soll.}
```suggestion
\colorbox{red}{Abschnitt: allgemeiner formulieren. Am Anfang wurde abgesprochen, dass es auch andere Services geben soll.}
```

2021-02-21 14:48 UTC, tcoro commented on docs/report/report.tex
> +\colorbox{orange}{als Fließtext}
```suggestion
\colorbox{red}{als Fließtext}
```

2021-02-21 14:48 UTC, tcoro commented on docs/report/report.tex
> +\colorbox{orange}{als Fließtext}
```suggestion
\colorbox{red}{als Fließtext}
```

2021-02-21 14:48 UTC, tcoro commented on docs/report/report.tex
> +\colorbox{orange}{kurzer text der zu NFC-Tags allgemein schreibt}
```suggestion
\colorbox{red}{lesen und schreiben vlt als ein gemeinsamer Abschnitt}
\colorbox{red}{kurzer text der zu NFC-Tags allgemein schreibt}
```

2021-02-21 14:48 UTC, tcoro commented on docs/report/report.tex
> +\colorbox{orange}{warum Docker? warum virtualisierung?}
```suggestion
\colorbox{red}{warum Docker? warum virtualisierung?}
```

2021-02-21 14:48 UTC, tcoro commented on docs/report/report.tex
> +\colorbox{orange}{warum die? wofür sind die?}
```suggestion
\colorbox{red}{warum die? wofür sind die?}
```

2021-02-21 14:48 UTC, tcoro commented on docs/report/report.tex
> +\colorbox{orange}{warum ist das interassant?}
```suggestion
\colorbox{red}{warum ist das interassant?}
```

2021-02-21 14:48 UTC, tcoro commented on docs/report/report.tex
> +\colorbox{orange}{warum so? was ist die Alternative?}
```suggestion
\colorbox{red}{warum so? was ist die Alternative?}
```

2021-02-21 14:48 UTC, tcoro commented on docs/report/report.tex
> +\colorbox{orange}{weniger umgangssprachlich und mehr}
```suggestion
\colorbox{red}{weniger umgangssprachlich und mehr}
```

2021-02-21 14:48 UTC, tcoro commented on docs/report/report.tex
> +\colorbox{orange}{spotify als einen Abschnitt und zu den anderen Services}
```suggestion
\colorbox{red}{spotify als einen Abschnitt und zu den anderen Services}
```

2021-02-21 14:48 UTC, tcoro commented on docs/report/report.tex
> +\colorbox{orange}{components und reactivity sollten noch beschrieben werden!}
```suggestion
\colorbox{red}{components und reactivity sollten noch beschrieben werden!}
```

2021-02-21 14:48 UTC, tcoro commented on docs/report/report.tex
> +\colorbox{orange}{Hier ggf. nochmal die Satzstrukturanpassen ist alles sehr parataktisch}
```suggestion
\colorbox{red}{Hier ggf. nochmal die Satzstrukturanpassen ist alles sehr parataktisch}
```

2021-02-21 15:17 UTC, JanEberlein commented on docs/report/report.tex
> +\colorbox{orange}{Ja und? warum ist das relevant? was bedeutet das für unser Projekt}
Ist nicht nötig, mit package xcolor geht das 😄

2021-02-21 15:21 UTC, JanEberlein commented
> orange als colorbox geht nicht

Doch 😜 aber nur mit package xcolor

2021-02-21 18:00 UTC, schnickalodeon approved these changes

2021-02-22 11:19 UTC, tcoro approved these changes

2021-02-22 11:19 UTC, merged