441 Ausblick
project-leek/project-leek pull request #463
Opened 2021-02-17 16:02 UTC by JanEberlein

2021-02-17 17:04 UTC, tcoro requested changes
Eine orangebox falls wir mehr text brauhcen, und irgendwo noch hinzufügen dass ne 3d printbare box auch in aussicht wäre, von der auch die open source community was hätte

2021-02-17 17:04 UTC, tcoro commented on docs/report/report.tex
> +Auch die Benutzeroberfläche für die NFC-Tag-Konfiguration sollte noch weiter überarbeitet werden.
```suggestion
Auch die Benutzeroberfläche für die NFC-Tag-Konfiguration sollte noch weiter überarbeitet werden. \colorbox{orange}{um was erweitert?}
```

2021-02-17 19:38 UTC, schnickalodeon commented on docs/report/report.tex
> +Am Ende der Bearbeitungszeit steht nun ein Produkt, welches die Mindestanforderungen erfüllt.
```suggestion
Am Ende der Bearbeitungszeit hat das Team ein Produkt geschaffen, welches die Mindestanforderungen, die vom Kunden gestellt wurden erfüllt.
```

2021-02-17 19:52 UTC, schnickalodeon requested changes
Der Text klingt irgendwie ganz schön negativ. Ich würde eher darauf eingehen, dass wir ein super Produkt haben und alle Minimal Requirements umgesetzt haben ABER es halt ein immer weiter laufendes OpenSource Produkt ist, wo noch die Vorschläge von macio wie die weitere Implementierung von mehreren Music-Services möglich ist. Aber macio meinte ja selbst von Anfang an, dass sie nicht davon ausgehen, dass wir das schaffen werden.

Im Allgemeinen ist der Text auch wieder sehr Parataktisch. Können wir bei Bedarf auch nochmal gerne zusammen drübergucken

2021-02-17 19:52 UTC, schnickalodeon commented on docs/report/report.tex
> +Dennoch bleiben noch viele der anfänglichen Wünsche und Vorstellungen offen.
```suggestion
Dennoch bleiben noch einige der anfänglichen Wünsche und Vorstellungen offen.
```

2021-02-17 19:52 UTC, schnickalodeon commented on docs/report/report.tex
> +Auch die Benutzeroberfläche für die NFC-Tag-Konfiguration sollte noch weiter überarbeitet werden.
Ich würde den Punkt glaube ich auch rauslassen. Und wenn nicht, dann

```suggestion
Auch die Benutzeroberfläche für die NFC-Tag-Konfiguration könnte noch weiter überarbeitet werden.
```

2021-02-17 19:52 UTC, schnickalodeon commented on docs/report/report.tex
> +Diese könnten dann in gleicher Weise zur Anmeldung und zum Hinzufügen und Abspielen von Musik genutzt werden.
```suggestion
Aber vor allem sollten andere Musikstreaming-Services neben Spotify eingebunden werden,
welche dann in gleicher Weise zur Anmeldung und zum Hinzufügen und Abspielen von Musik genutzt werden.
```

2021-02-17 19:52 UTC, schnickalodeon commented on docs/report/report.tex
> +All diese Dinge hätte das Team gerne umgesetzt, dies war aber mit dem sehr knappen Zeitrahmen nicht umsetzbar.
Auch da nicht unbedingt sagen, dass keine Zeit war sondern das eher als. "Hey, das wäre doch noch eins flonkes feature" verkaufen

2021-02-17 19:52 UTC, schnickalodeon commented on docs/report/report.tex
> +Des weiteren besteht auch die Hoffnung, dass macio viel aus diesem Projekt gelernt hat und auch fortlaufend weiter daraus lernen wird.
Dass macio was gelernt hat?

2021-02-18 14:42 UTC, JanEberlein commented on docs/report/report.tex
> +Des weiteren besteht auch die Hoffnung, dass macio viel aus diesem Projekt gelernt hat und auch fortlaufend weiter daraus lernen wird.
```suggestion
Des weiteren besteht auch die Hoffnung, dass macio viel von der Organisation dieses Projekts gelernt hat und auch fortlaufend weiter daraus lernen wird.
```

2021-02-18 14:53 UTC, JanEberlein commented on docs/report/report.tex
> +Auch die Benutzeroberfläche für die NFC-Tag-Konfiguration sollte noch weiter überarbeitet werden.
```suggestion
Auch die Benutzeroberfläche für die NFC-Tag-Konfiguration könnte noch weiter optimiert werden.
```

2021-02-19 12:05 UTC, JanEberlein commented on docs/report/report.tex
> +All diese Dinge hätte das Team gerne umgesetzt, dies war aber mit dem sehr knappen Zeitrahmen nicht umsetzbar.
```suggestion
```

2021-02-19 14:01 UTC, tcoro requested changes
Kleinigkeiten

2021-02-21 18:30 UTC, JanEberlein commented on docs/report/report.tex
> +Dennoch bleiben noch einige der anfänglichen Wünsche und Vorstellungen offen.
```suggestion
Darüber hinaus gibt es noch einige weitere Aspekte der Produktvision, die noch umgesetzt werden könnten.
```

2021-02-22 11:17 UTC, tcoro approved these changes

2021-02-22 19:38 UTC, schnickalodeon approved these changes

2021-02-22 19:40 UTC, merged