456 milestone 2
project-leek/project-leek pull request #464
Opened 2021-02-17 19:34 UTC by schnickalodeon

closes #456

2021-02-19 08:12 UTC, tcoro approved these changes
get some sleep 💤 😴 ❤️

2021-02-19 08:12 UTC, tcoro commented on docs/report/report.tex
> +wurde. Sie behinhaltete Attribute wie \glqq Name \grqq{} oder \glqq Id \grqq. Auf dieser Basis wurde anschließend ein Feathers-Service in Form einer
```suggestion
wurde. Sie beinhaltete Attribute wie \glqq Name \grqq{} oder \glqq Id \grqq. Auf dieser Basis wurde anschließend ein Feathers-Service in Form einer
```

2021-02-19 08:12 UTC, tcoro commented on docs/report/report.tex
> +die zuvor erstellte Modell-Klasse angegeben. Um z. B. Objekte der Klasse \textit{NicksPet} zu verwlaten wurde folgender Service angelegt:
```suggestion
die zuvor erstellte Model-Klasse angegeben. Um z. B. Objekte der Klasse \textit{NicksPet} zu verwalten wurde folgender Service angelegt:
```

2021-02-19 08:12 UTC, tcoro commented on docs/report/report.tex
> +verwaltet werden sollen (in diesem Fall mit der durch \textit{Feathers} bereitgestellten Schnitstelle für die Datenbank \textit{NeDB}).
```suggestion
verwaltet werden sollen (in diesem Fall mit der durch \textit{Feathers} bereitgestellten Schnittstelle für die Datenbank \textit{NeDB}).
```

2021-02-19 08:12 UTC, tcoro commented on docs/report/report.tex
> +und die Arbeit im Backend abgeschlossen. Der nächste Schritt behinhaltete die Implemntierung der Steuerelemente zum Verwalten der Daten im Frontend.
```suggestion
und die Arbeit im Backend abgeschlossen. Der nächste Schritt beinhaltete die Implementierung der Steuerelemente zum Verwalten der Daten im Frontend.
```

2021-02-19 08:12 UTC, tcoro commented on docs/report/report.tex
> +Aufgrund der erhöten Komplexität der Einarbeitung in mehrere teilweise komplett unbekannte Frameworks zur selben Zeit, bestanden bei dieser Aufgabe
```suggestion
Aufgrund der erhöhten Komplexität der Einarbeitung in mehrere teilweise komplett unbekannte Frameworks zur selben Zeit, bestanden bei dieser Aufgabe
```

2021-02-19 08:12 UTC, tcoro commented on docs/report/report.tex
> +Im Frontend wurde pro Haustier je ein \textit{compontet} zur Anzeige eines Haustiers angelegt,
```suggestion
Im Frontend wurde pro Haustier je ein \textit{component} zur Anzeige eines Haustiers angelegt,
```

2021-02-19 08:12 UTC, tcoro commented on docs/report/report.tex
> +simmuliert dabei eine Tastatureingabe mit dem Text der NFC-Tag-ID. Zur Nutzung wurden zwei Klassen erstellt. Zum einen die NFC-Reader Klasse
```suggestion
simuliert dabei eine Tastatureingabe mit dem Text der NFC-Tag-ID. Zur Nutzung wurden zwei Klassen erstellt. Zum einen die NFC-Reader Klasse
```

2021-02-19 08:12 UTC, tcoro commented on docs/report/report.tex
> +(im NFC-Reader Package), welche jeden simmulierten Tastendruck des NFC-Readers abfängt, bis ein Zeileumbruch (0A HEX) empfangen
```suggestion
(im NFC-Reader Package), welche jeden simulierten Tastendruck des NFC-Readers abfängt, bis ein Zeilenumbruch (0A HEX) empfangen
```

2021-02-19 08:12 UTC, tcoro commented on docs/report/report.tex
> +wird und anschließend ein Event auslöst, welches die eingescante ID beinhaltet. Die Hauptklasse nimmt dieses Event entgegen (Event-Listener) und setzt mittels des
```suggestion
wird und anschließend ein Event auslöst, welches die eingescannte ID beinhaltet. Die Hauptklasse nimmt dieses Event entgegen (Event-Listener) und setzt mittels des
```

2021-02-19 08:12 UTC, tcoro commented on docs/report/report.tex
> +NFC-Reader Services den aktuell anliegenen Tags (\textit{currentTag}) auf die übergebene ID. Durch die Nutzung von \textit{Web-Sockets} und \textit{Vue.js}
```suggestion
NFC-Reader Services den aktuell anliegenden Tags (\textit{currentTag}) auf die übergebene ID. Durch die Nutzung von \textit{Web-Sockets} und \textit{Vue.js}
```

2021-02-19 08:12 UTC, tcoro commented on docs/report/report.tex
> +\colorbox{red}{Hier bei Bedarf noch weiter ausführen (aber wäre sehr ins Detail gegeangen)}
würde orange colorbox für textfüllstellen behalten
```suggestion
\colorbox{orange}{Hier bei Bedarf noch weiter ausführen (aber wäre sehr ins Detail gegeangen)}
```

2021-02-19 08:12 UTC, tcoro requested changes
hopppala, solte n request change werden

2021-02-19 09:58 UTC, tcoro commented on docs/report/report.tex
>  Zur Abstimmung auf ein Design für die Benutzeroberfläche wurden vor der Entwicklung Prototypen der benötigeten Komponenten mittels des webbaiserten
```suggestion
Zur Abstimmung auf ein Design für die Benutzeroberfläche wurden vor der Entwicklung Prototypen der benötigten Komponenten mittels des webbasierten
```
noch zwei typos gefunden

2021-02-19 13:52 UTC, schnickalodeon commented
Danke @tcoro keine Ahnung was da mit mir los war ^^

2021-02-19 13:53 UTC, tcoro approved these changes

2021-02-19 16:58 UTC, JanEberlein requested changes

2021-02-19 16:58 UTC, JanEberlein commented on docs/report/report.tex
> +Möglichkeit NFC-Tags auszulesen implementiert werden. Diese Anforderung geriet mangels ausreichender Notizen beim ersten Review vorerst
```suggestion
Neben der Umsetzung des Hello-Worlds sollte sich mit dem Raspberry Pi und dem NFC-Reader auseinandergesetzt und das Auslesen der NFC-Tags implementiert werden. Diese Anforderung geriet mangels ausreichender Notizen beim ersten Review vorerst
```

2021-02-21 13:56 UTC, JanEberlein approved these changes

2021-02-21 13:56 UTC, merged