455 milestone 3
project-leek/project-leek pull request #467
Opened 2021-02-18 19:56 UTC by schnickalodeon

closes #455

2021-02-19 13:48 UTC, schnickalodeon commented
Meine Punkte sind soweit umgesetzt. Wenn der Teil mit Github IO fertig ist, bitte nochmal Korrekturlesen und auf "Ready for Review" stellen @anbraten

2021-02-19 14:18 UTC, anbraten requested changes

2021-02-19 14:18 UTC, anbraten commented on docs/report/report.tex
> +\colorbox{red}{@Anbraten hier bitte auführen}
I will add my part here.

2021-02-20 12:09 UTC, anbraten commented on docs/report/report.tex
> +\colorbox{red}{@Anbraten hier bitte auführen}
We be done in separate PR.

2021-02-20 12:09 UTC, anbraten approved these changes

2021-02-20 13:01 UTC, tcoro approved these changes
top top

2021-02-20 13:01 UTC, merged