451 milestone 7
project-leek/project-leek pull request #468
Opened 2021-02-19 10:43 UTC by tcoro

2021-02-20 10:43 UTC, schnickalodeon reviewed
Sehr gut. Damit sind wir ja auch noch nicht fertig. Deswegen ist es schwer damit schon großartig weiterzumachen. Du könntest dann noch darauf eingehen, wie die Präsentation erstellt wurde. Also PowerPoint usw. und welche genaueren Gedanken dabei aufgetreten sind. Ist aber erstmal glaube ich nicht so dringend. Erstmal gucken wie viele Seiten wir so zusammen bekommen

2021-02-22 19:20 UTC, JanEberlein requested changes
Größtenteils Kleinkram

2021-02-22 19:20 UTC, JanEberlein commented on docs/report/report.tex
> +Nach erneuter Rücksprache mit dem Prüfenden ergab sich die Anforderung für den Bericht von 50-60 Seiten ohne Anhang.
```suggestion
Nach erneuter Rücksprache mit ergab sich die Anforderung für den Bericht von 50-60 Seiten (ohne Anhang).
```

2021-02-22 19:20 UTC, JanEberlein commented on docs/report/report.tex
> +Daher traf sich zu Beginn das Team , um den Bericht gemeinsam durchzugehen und ggf. zu ändern.
```suggestion
Daher traf sich zu Beginn das Team, um den Bericht gemeinsam durchzugehen und ggf. zu ändern.
```

2021-02-22 19:20 UTC, JanEberlein commented on docs/report/report.tex
> +Die Meilensteine wurden daher ausführlicher behandelt, es wurde mehr auf die Durchführengen und Herangehensweisen eingegangen.
```suggestion
Die Meilensteine wurden ausführlicher behandelt und es wurde mehr auf die Durchführung und Herangehensweisen eingegangen.
```

2021-02-22 19:20 UTC, JanEberlein commented on docs/report/report.tex
> +Da die erste Version des Berichtes zu Beginn des Sprints noch nicht fertig war, musste das Team dies Zeitig erledigen, um noch erste Anmerkungen vom Prüfenden erhalten und korrigieren zu können.
```suggestion
Da die erste Version des Berichtes zu Beginn des Sprints noch nicht fertig war, musste das Team dies zeitig erledigen, um noch erste Anmerkungen vom Prüfenden erhalten und korrigieren zu können.
```

2021-02-22 19:20 UTC, JanEberlein commented on docs/report/report.tex
> +Umgesetzter Quellcode wurde dort hinzugefügt, behandelt und erklärt.
```suggestion
Wichtiger und zentraler Quellcode wurde hier hinzugefügt, behandelt und erklärt.
```

2021-02-22 19:20 UTC, JanEberlein commented on docs/report/report.tex
> +Auch fehlten an vielen Stellen Bilder und Beispiele, die das jeweilige Problem besser veranschaulichen.
```suggestion
Auch fehlten an vielen Stellen Bilder und Beispiele, die die jeweiligen Probleme, Lösungen und Ansätze besser veranschaulichen.
```

2021-02-22 19:20 UTC, JanEberlein commented on docs/report/report.tex
> +Am Ende dieser Präsentation sollte der Prüfende die Arbeitsleistung des Teams evaluieren können, der Kunde das Produkt selbstständig nutzen und weiterentwickeln können.
```suggestion
Am Ende dieser Präsentation sollte der Prüfende die Arbeitsleistung des Teams evaluieren können und der Kunde das Produkt selbstständig nutzen und weiterentwickeln können.
```

2021-02-22 19:27 UTC, tcoro commented on docs/report/report.tex
> +Nach erneuter Rücksprache mit dem Prüfenden ergab sich die Anforderung für den Bericht von 50-60 Seiten ohne Anhang.
```suggestion
Nach erneuter Rücksprache  ergab sich die Anforderung für den Bericht von 50-60 Seiten (ohne Anhang).
```

2021-02-22 19:28 UTC, tcoro commented on docs/report/report.tex
> +Daher traf sich zu Beginn das Team , um den Bericht gemeinsam durchzugehen und ggf. zu ändern.
?

2021-02-22 19:32 UTC, JanEberlein commented on docs/report/report.tex
> +Daher traf sich zu Beginn das Team , um den Bericht gemeinsam durchzugehen und ggf. zu ändern.
leerzeichen vorm komma

2021-02-22 19:35 UTC, schnickalodeon requested changes
Blub die zweite

2021-02-22 19:35 UTC, schnickalodeon commented on docs/report/report.tex
> +Da die erste Version des Berichtes zu Beginn des Sprints noch nicht fertig war, musste das Team dies Zeitig erledigen, um noch erste Anmerkungen vom Prüfenden erhalten und korrigieren zu können.
```suggestion
Da die erste Version des Berichtes zu Beginn des Sprints noch nicht abgeschlossen war, musste das Team dies zeitig erledigen, um noch erste Anmerkungen vom Prüfenden erhalten und anschließend korrigieren zu können.
```

2021-02-22 19:35 UTC, schnickalodeon commented on docs/report/report.tex
> +Nach erneuter Rücksprache mit dem Prüfenden ergab sich die Anforderung für den Bericht von 50-60 Seiten ohne Anhang.
```suggestion
Nach erneuter Rücksprache mit dem Prüfenden ergab sich ein geforderter Umfang von 50-60 Seiten für den Bericht (exklusive Anhang).
```

2021-02-22 19:35 UTC, schnickalodeon commented on docs/report/report.tex
> +Mit dem bisherigen Entwurf und noch geplanten Abschnitten wäre es dem Team sehr schwer gefallen, diese Anforderung umzusetzen.
```suggestion
Mit der zu diesem Zeitpunkt angedachten Struktur wäre die Erfüllung dieser Anforderung erschwert worden.
```

2021-02-22 19:35 UTC, schnickalodeon commented on docs/report/report.tex
> +Dabei ergaben sich verschiedene Änderungen:\\
```suggestion
Um diese Anforderung dennoch umzusetzen, prüfte das Team den Bericht und verständigte sich auf  folgende Änderungen:
```

2021-02-22 19:35 UTC, schnickalodeon commented on docs/report/report.tex
> +Die Meilensteine wurden daher ausführlicher behandelt, es wurde mehr auf die Durchführengen und Herangehensweisen eingegangen.
```suggestion
Die Meilensteine sollten ausführlicher behandelt, indem mehr auf die jeweilige Durchführung und Herangehensweisen eingegangen werden sollte;
```

2021-02-22 19:35 UTC, schnickalodeon commented on docs/report/report.tex
> +Umgesetzter Quellcode wurde dort hinzugefügt, behandelt und erklärt.
```suggestion
Umgesetzter Quellcode sollte hinzugefügt, behandelt und erklärt werden.
```

2021-02-22 19:35 UTC, schnickalodeon commented on docs/report/report.tex
> +Auch fehlten an vielen Stellen Bilder und Beispiele, die das jeweilige Problem besser veranschaulichen.
```suggestion
Zusätzlich sollten die Ausführungen um Bilder und Beispiele, die das jeweilige Problem besser veranschaulichen ergänzt werden.
```

2021-02-22 19:35 UTC, schnickalodeon commented on docs/report/report.tex
> +Auch sollte das finale Produkt und deren Funktionsweise dem Kunden erklärt werden.
```suggestion
In dieser sollte dem Prüfenden sowie dem Projektbegleitenden Unternehmen macio die Iterationen des Projektes und das Produkt präsentiert werden.
```

2021-02-22 19:35 UTC, schnickalodeon commented on docs/report/report.tex
> +Am Ende dieser Präsentation sollte der Prüfende die Arbeitsleistung des Teams evaluieren können, der Kunde das Produkt selbstständig nutzen und weiterentwickeln können.
```suggestion
Am Ende dieser Präsentation sollte der Prüfende die Arbeitsleistung des Teams anhand des Berichts und der Zufriedenheit des Kunden evaluieren können. Außerdem sollte der Kunde das Produkt selbstständig nutzen und weiterentwickeln können.
```

2021-02-22 19:40 UTC, schnickalodeon approved these changes
blubidiblub

2021-02-22 19:52 UTC, JanEberlein requested changes
nochmal die 'outdated' Kommentare von @schnickalodeon

2021-02-22 19:52 UTC, JanEberlein commented on docs/report/report.tex
> +Da die erste Version des Berichtes zu Beginn des Sprints noch nicht fertig war, musste das Team dies zeitig erledigen, um noch erste Anmerkungen vom Prüfenden erhalten und korrigieren zu können.
```suggestion
Da die erste Version des Berichtes zu Beginn des Sprints noch nicht abgeschlossen war, musste das Team dies zeitig erledigen, um noch erste Anmerkungen vom Prüfenden erhalten und anschließend korrigieren zu können
```

2021-02-22 19:52 UTC, JanEberlein commented on docs/report/report.tex
> +Nach erneuter Rücksprache ergab sich die Anforderung für den Bericht von 50-60 Seiten (ohne Anhang).
```suggestion
Nach erneuter Rücksprache mit diesem ergab sich ein geforderter Umfang von 50-60 Seiten für den Bericht (exklusive Anhang).
```

2021-02-22 19:52 UTC, JanEberlein commented on docs/report/report.tex
> +Dabei ergaben sich verschiedene Änderungen:\\
```suggestion
Um diese Anforderung dennoch umzusetzen, prüfte das Team den Bericht und verständigte sich auf  folgende Änderungen:\\
```

2021-02-22 19:52 UTC, JanEberlein commented on docs/report/report.tex
> +Die Meilensteine wurden ausführlicher behandelt und es wurde mehr auf die Durchführung und Herangehensweise eingegangen.
```suggestion
Die Meilensteine sollten ausführlicher behandelt, indem mehr auf die jeweilige Durchführung und Herangehensweisen eingegangen werden sollte;
```

2021-02-22 19:52 UTC, JanEberlein commented on docs/report/report.tex
> +Wichtiger und zentraler Quellcode wurde hier hinzugefügt, behandelt und erklärt.
```suggestion
Wichtiger und zentraler Quellcode sollte hier hinzugefügt, behandelt und erklärt werden.
```

2021-02-22 19:52 UTC, JanEberlein commented on docs/report/report.tex
> +Auch fehlten an vielen Stellen Bilder und Beispiele, die die jeweiligen Probleme, Lösungen und Ansätze besser veranschaulichen.
```suggestion
Zusätzlich sollten die Ausführungen um Bilder und Beispiele, die das jeweilige Problem besser veranschaulichen ergänzt werden.
```

2021-02-22 19:52 UTC, JanEberlein commented on docs/report/report.tex
> +Am Ende dieser Präsentation sollte der Prüfende die Arbeitsleistung des Teams evaluieren können und der Kunde das Produkt selbstständig nutzen und weiterentwickeln können.
```suggestion
Am Ende dieser Präsentation sollte der Prüfende die Arbeitsleistung des Teams anhand des Berichts und der Zufriedenheit des Kunden evaluieren können. Außerdem sollte der Kunde das Produkt selbstständig nutzen und weiterentwickeln können.
```

2021-02-22 19:55 UTC, JanEberlein approved these changes

2021-02-22 19:55 UTC, merged