452 mmilestone-6
project-leek/project-leek pull request #472
Opened 2021-02-19 13:01 UTC by tcoro

2021-02-20 10:36 UTC, schnickalodeon commented on docs/report/report.tex
> +Der \textit{Button Component} wurde refactored, dass auch dieser universell für alle Anwendungszwecke genutzt werden konnte.
Was wurde verändert?
das könnte man beschreiben

2021-02-20 10:37 UTC, schnickalodeon commented on docs/report/report.tex
> +Die Verbindung zwischen Frontend und Backend wurde auch anstelle einer Ip Adresse ersetzt durch ngrok. \colorbox{red}{was genau macht ngrok?}
Was ngrok macht musst du nicht schreiben. Das hab ich schon unter Technologien gemacht. Kannst du drauf verweisen

2021-02-20 10:40 UTC, schnickalodeon reviewed
Ab hier wird es wirklich schwer mit dem erhöhten Detailgrad

2021-02-21 12:29 UTC, tcoro commented on docs/report/report.tex
> +Die Verbindung zwischen Frontend und Backend wurde auch anstelle einer Ip Adresse ersetzt durch ngrok. \colorbox{red}{was genau macht ngrok?}
wurde gestrichen

2021-02-21 16:58 UTC, tcoro commented on docs/report/report.tex
> +Der \textit{Button Component} wurde refactored, dass auch dieser universell für alle Anwendungszwecke genutzt werden konnte.
done

2021-02-22 19:12 UTC, schnickalodeon requested changes
Blub

2021-02-22 19:12 UTC, schnickalodeon commented on docs/report/report.tex
> +Anfänglich wurden die Kapitel und Abschnitte für einen insgesamt runderen roten Faden im Bericht überarbeitet.
```suggestion
Anfänglich wurden die Kapitel und Abschnitte zur Optimierung der Berichtsstruktur überarbeitet.
```

2021-02-22 19:12 UTC, schnickalodeon commented on docs/report/report.tex
> +Aus diesen wurden entsprechend die Tickets im Ticket Pool erstellt, die sich die einzelnen Teammitglieder zuweisen können.
```suggestion
Die daraus resultierenden Änderungen wurden in Tickets überführt, die sich die einzelnen Teammitglieder zuweisen konnten.
```

2021-02-22 19:12 UTC, schnickalodeon commented on docs/report/report.tex
> +Dies hatte den Vorteil, wie bei der Softwareentwicklung auch bei der Dokumentationsarbeit eine Übersicht zu haben, welche Teile des Berichtes bereits bearbeitet werden, welche noch offen sind, wievie
```suggestion
Dies hatte den Vorteil dass, wie schon bei der Softwareentwicklung eine kontinuierliche Übersicht über den Fortschritt der Berichtsarbeit herrschte. 
```

2021-02-22 19:12 UTC, schnickalodeon commented on docs/report/report.tex
> +Nur etwas mehr als die Hälfte das Berichtes konnte umgesetzt werden.
```suggestion
Dies hatte zur Folge, dass zum Ende des Sprints nur etwas mehr als die Hälfte des Berichts abgeschlossen war. Somit konnte dem Prüfenden nicht die erste Version des Berichtes vorgelegt werden und das Team bekam somit verspätet erstes Feedback.
```

2021-02-22 19:12 UTC, schnickalodeon commented on docs/report/report.tex
> +So konnte auch weiterhin der Workflow genutzt werden, dass mit Pull Requests und mindestens zwei Reviewern gearbeitet werden muss.
```suggestion
Dass der Bericht mit \textit{LaTeX} geschrieben wurde hatte den Vorteil, dass Git sinnvoll genutzt werden konnte und die Änderungen der jeweiligen Mitglieder schnell ersichtlich waren.
So konnte auch weiterhin der Workflow mit \textit{Pull Requests} und zwei \textit{Code Reviews} genutzt werden.
```

2021-02-22 19:39 UTC, schnickalodeon approved these changes

2021-02-22 19:57 UTC, julianhahn approved these changes
lgtm

2021-02-22 19:58 UTC, merged