513 dynamisches Testen Beispiel
project-leek/project-leek pull request #520
Opened 2021-02-25 14:10 UTC by JanEberlein

2021-02-25 14:59 UTC, julianhahn requested changes
Was hälst du von den alternativen formulierungen?

2021-02-25 14:59 UTC, julianhahn commented on docs/report/report.tex
> +    Bei diese Testfällen werden User-Stories Schritt für Schritt \glqq durchgespielt\grqq{} und dabei überprüft, ob das Verhalten dem erwartetem entspricht.
```suggestion
    Bei diese Testfällen werden User-Stories Schritt für Schritt \glqq durchgespielt\grqq{} und dabei überprüft, ob das Resultat  dem erwarteten Verhalten entspricht.
```
Nur als Vorschlag

2021-02-25 14:59 UTC, julianhahn commented on docs/report/report.tex
> +    Für die testenden Entwickler bedeutete das konkret, bei der Überprüfung folgende Schritte zu durchlaufen:
```suggestion
    Die testenden Entwickler durchliefen bei der Überprüfung folgende Schritte:
```

2021-02-25 15:57 UTC, JanEberlein commented on docs/report/report.tex
> +    Bei diese Testfällen werden User-Stories Schritt für Schritt \glqq durchgespielt\grqq{} und dabei überprüft, ob das Verhalten dem erwartetem entspricht.
klingt gut

2021-02-25 18:48 UTC, julianhahn requested changes
noch ein typo dann darfs rein

2021-02-25 18:48 UTC, julianhahn commented on docs/report/report.tex
> +    Bei diese Testfällen werden User-Stories Schritt für Schritt \glqq durchgespielt\grqq{} und dabei überprüft, ob das Resultat  dem erwarteten Verhalten entspricht.
```suggestion
    Bei diesen Testfällen werden User-Stories Schritt für Schritt \glqq durchgespielt\grqq{} und dabei überprüft, ob das Resultat  dem erwarteten Verhalten entspricht.
```

2021-02-25 18:53 UTC, julianhahn approved these changes

2021-02-26 10:06 UTC, schnickalodeon approved these changes
Jetzt wird es sehr klar. Top :)

2021-02-26 10:06 UTC, merged