486 microservice mit diagram beschreiben
project-leek/project-leek pull request #524
Opened 2021-02-26 12:50 UTC by JanEberlein

closes #486

2021-02-26 13:29 UTC, julianhahn requested changes
sieht gut aus

2021-02-26 13:29 UTC, julianhahn commented on docs/report/report.tex
> +  Diese kommunizieren untereinander mit allgemein verwendeten Protokollen wie zum Beispiel HTTP via APIs.
```suggestion
  Diese kommunizieren untereinander mit allgemein verwendeten Protokollen, wie zum Beispiel HTTP, via APIs.
```

2021-02-26 14:01 UTC, tcoro approved these changes
noch julians changes und dann go go

2021-02-27 07:59 UTC, julianhahn approved these changes

2021-02-27 08:22 UTC, merged