Antonskram
project-leek/project-leek pull request #525
Opened 2021-02-26 13:13 UTC by schnickalodeon

closes nothing

2021-02-26 13:27 UTC, tcoro commented
closes nothing?
ist doch https://github.com/project-leek/project-leek/issues/494 und https://github.com/project-leek/project-leek/issues/495 oder nicht?

2021-02-26 13:31 UTC, tcoro requested changes
kleinigkeiten

2021-02-26 13:31 UTC, tcoro commented on docs/report/report.tex
> +Dieser bestand darin, dass der Container des NFC-Readers versuchte, seine Id in diesem zu setzen, bevor er eine Verbindung zu dem Backend aufgebaut hatte.
```suggestion
Dieser bestand darin, dass der Container des NFC-Readers versuchte, seine \textit{Id} in diesem zu setzen, bevor er eine Verbindung zu dem Backend aufgebaut hatte.
```
maybe?

2021-02-26 13:31 UTC, tcoro commented on docs/report/report.tex
> +Dies konnte gelöst werden, indem ein \textit{Event-Listener}, der die ID in der Datenbank des Backend setzt, auf das \textit{connect}-Event registriert wurde.
```suggestion
Dies konnte gelöst werden, indem ein \textit{Event-Listener}, der die \texit{Id} in der Datenbank des Backend setzt, auf das \textit{connect}-Event registriert wurde.
```
same here?

2021-02-26 13:31 UTC, tcoro commented on docs/report/report.tex
> +Zur Behebung dieses Problems wurde eine Offline-Seite konzipiert, die Informationen über den Fehler bereitstellt und die Eingabe einer neuen Adresse ermgölicht.
```suggestion
Zur Behebung dieses Problems wurde eine Offline-Seite konzipiert, die Informationen über den Fehler bereitstellt und die Eingabe einer neuen Adresse ermöglicht.
```

2021-02-26 16:09 UTC, JanEberlein requested changes
noch ein paar Dinge

2021-02-26 16:09 UTC, JanEberlein commented on docs/report/report.tex
> +Das Frontend ist vom Raspberry zu Github.io Pages umgezogen.
```suggestion
Das Frontend ist vom Raspberry Pi zu Github.io Pages umgezogen.
```

2021-02-26 16:09 UTC, JanEberlein commented on docs/report/report.tex
> +bereitgestellt wird. Daraufhin kann sich der Benutzer über \textit{project-leek.github.io} durch die Eingabe dieser Adresse mit der neuen \textit{Leek-Box} verbinden. Da in der App zu diesem Zeitpunk
```suggestion
bereitgestellt wird. Daraufhin kann sich der Benutzer über \url{project-leek.github.io} durch die Eingabe dieser Adresse mit der neuen \textit{Leek-Box} verbinden. Da in der App zu diesem Zeitpunkt noch kein
```

2021-02-27 08:03 UTC, anbraten approved these changes

2021-02-27 08:09 UTC, tcoro approved these changes

2021-02-27 08:09 UTC, JanEberlein approved these changes

2021-02-27 08:11 UTC, merged