hello world tom
project-leek/project-leek pull request #56
Opened 2020-11-17 21:36 UTC by anbraten

2020-11-18 08:41 UTC, anbraten commented on packages/app/src/components/HelloWorld.vue
> +import { Rudolfo } from '../../../backend/node_modules/@project-leek/commons/dist';
```suggestion
import { Rudolfo } from '@project-leek/commons';
```

2020-11-24 19:59 UTC, JanEberlein approved these changes

2020-11-24 20:10 UTC, julianhahn requested changes

2020-11-24 20:10 UTC, julianhahn commented on packages/backend/src/services/rudolfo/rudolfo.model.ts
> +    autoload: true,
you could add  the following line after autoload, for the test to pass alyways
`inMemoryOnly: process.env.NODE_ENV === 'test',`

2020-11-24 20:14 UTC, julianhahn approved these changes

2020-11-24 20:15 UTC, merged