Update README.md
project-leek/project-leek pull request #63
Opened 2020-11-22 12:53 UTC by julianhahn

Change Readme to adivse users about a problem with wsl

2020-11-22 17:28 UTC, anbraten approved these changes

2020-11-23 13:26 UTC, anbraten requested changes

2020-11-23 13:26 UTC, anbraten commented on README.md
>  Checkout project locally. Enter the project folder and run:
We should add a blank line here. As the second part should not be part of the hint.

```suggestion

Checkout project locally.
Enter the project folder and run:
```

2020-11-24 17:17 UTC, JanEberlein approved these changes

2020-11-24 17:20 UTC, anbraten approved these changes

2020-11-24 17:23 UTC, merged